/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api/auth/$";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: "/api/auth/$",
  path: "/api/auth/$",
  getParentRoute: () => rootRouteImport,
} as any);

const LoginRoute = IndexRouteImport.update({
  id: "/Login",
  path: "/Login",
  getParentRoute: () => rootRouteImport,
} as any);

const ProtectedRoute = IndexRouteImport.update({
  id: "/_protected",
  path: "/_protected",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/Login": typeof LoginRoute;
  "/_protected": typeof ProtectedRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/Login": typeof LoginRoute;
  "/_protected": typeof ProtectedRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/api/auth/$": typeof ApiAuthSplatRoute;
  "/Login": typeof LoginRoute;
  "/_protected": typeof ProtectedRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/api/auth/$" | "/Login" | "/_protected";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/api/auth/$" | "/Login" | "/_protected";
  id: "__root__" | "/" | "/api/auth/$" | "/Login" | "/_protected";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
  LoginRoute: typeof LoginRoute;
  ProtectedRoute: typeof ProtectedRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/api/auth/$": {
      id: "/api/auth/$";
      path: "/api/auth/$";
      fullPath: "/api/auth/$";
      preLoaderRoute: typeof ApiAuthSplatRouteImport;
      parentRoute: typeof rootRouteImport;
    },
    "/Login": {
      id: "/Login";
      path: "/Login";
      fullPath: "/Login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    },
    "/_protected": {
      id: "/_protected";
      path: "/_protected";
      fullPath: "/_protected";
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  LoginRoute: LoginRoute,
  ProtectedRoute: ProtectedRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { createStart } from "@tanstack/react-start";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
  }
}
